services:
  redis: 
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456   
  mongo-express:
    image: mongo-express
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  rabbit:
    image: rabbitmq:3.13-management
    # environment:
    #   RABBITMQ_DEFAULT_VHOST: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  redis_data: